keys:
  - &nix-mgr age1fddrzze4llgrm87eudneguhpjm3al0h5urkwpvh8xf9wgtghmyfqftr7ue
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *nix-mgr
  - path_regex: secrets/atpki/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *nix-mgr
  - path_regex: secrets/nocmt01/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *nix-mgr
    