keys:
  - &nix-mgr age1fddrzze4llgrm87eudneguhpjm3al0h5urkwpvh8xf9wgtghmyfqftr7ue
  - &chisa age1n3u2cl6w3m693auxqwvayf0pzjg9m3kmraqtepcsf9ysyh4f348sjveq3t
  - &kyouka age18mxj9jae06at5tv9q6dk2t93v0n7c2lmcuml0qdskea2tncjlafshanl25
  - &rmnmvatpki age14g9f8nptt7z554qeuavjy2uczd0m6wlxddcgzmyvku34zp2grd8qd7nrl3
  - &rmnmvmgnix age1rmy535v6qmm552pzsvgjna4k4wmu2pjya796lm8k253pmfne3s0scn8zmz
  - &rmnmvnocmt01 age15kvyh0pjnv7ng09svtf2xtpqs89d6hxjxq7p07l2tnwcfe6p3y7qrhzkuv
  - &rmnmvadb02 age1ay20thc0y39hucs8mge0u448wgcn06gupf8332e0423uj330wdssfnpskj
  - &sumire age1sjaxe6w33yf8xuvwx732f6wfrx3398mcm9x6ajrvs5m520uduesszhy6xl
  - &uzuki age1srx92ehlpmrvw4uf0lrj6hu3fk6pdfhhuqja36qwxr0tvjfnsgmstckyru
  - &sajuna age1h6wq6zvrcfxnynkg09td8zpk0wnspnpe5pclmt2lzr85n0cx0d2qlwz3fx
  - &kumiko age16cdczm9a2jhy3p0jvw38s3yp4laqemc7axt7vs0zh4fxsracw9dsf846hc
  - &sena age1ga5n5vwl2qsptzs5lsxyregdlcs9pwshpfx8myvptfcr57dlxafsdamlyv
creation_rules:
  - path_regex: secrets(\\|/)[^/]+\.yaml$
    key_groups:
      - age:
        - *nix-mgr
        - *chisa
        - *kyouka
  - path_regex: secrets(\\|/)atpki(\\|/)[^/]+\.yaml$
    key_groups:
      - age:
        - *nix-mgr
        - *chisa
        - *kyouka
        - *rmnmvatpki
  - path_regex: secrets(\\|/)nocmt01(\\|/)[^/]+\.yaml$
    key_groups:
      - age:
        - *nix-mgr
        - *chisa
        - *kyouka
        - *rmnmvnocmt01
  - path_regex: secrets(\\|/)mgnix(\\|/)[^/]+\.yaml$
    key_groups:
      - age:
        - *nix-mgr
        - *chisa
        - *kyouka
        - *rmnmvmgnix
  - path_regex: secrets(\\|/)adb02(\\|/)[^/]+\.yaml$
    key_groups:
    - age:
      - *nix-mgr
      - *chisa
      - *kyouka
      - *rmnmvadb02
    encrypted_suffix: password
  - path_regex: secrets(\\|/)shitara(\\|/)[^/]+\.yaml$
    key_groups:
    - age:
      - *nix-mgr
      - *chisa
      - *kyouka
      - *sumire
      - *uzuki
      - *sajuna
      - *kumiko
      - *sena