keys:
  - &nix-mgr age1fddrzze4llgrm87eudneguhpjm3al0h5urkwpvh8xf9wgtghmyfqftr7ue
  - &chisa age1n3u2cl6w3m693auxqwvayf0pzjg9m3kmraqtepcsf9ysyh4f348sjveq3t
  - &kyouka age18mxj9jae06at5tv9q6dk2t93v0n7c2lmcuml0qdskea2tncjlafshanl25
  - &rmnmvatpki age14g9f8nptt7z554qeuavjy2uczd0m6wlxddcgzmyvku34zp2grd8qd7nrl3
creation_rules:
  - path_regex: secrets(\\|/)[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *nix-mgr
        - *chisa
        - *kyouka
  - path_regex: secrets(\\|/)atpki(\\|/)[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *nix-mgr
        - *chisa
        - *kyouka
        - *rmnmvatpki
  - path_regex: secrets(\\|/)nocmt01(\\|/)[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *nix-mgr
        - *chisa
        - *kyouka
