seaweedfs-security: ENC[AES256_GCM,data:prgL8d0tbF/PjxDqWkCje8fYq1kyGrqgbJJ6Y/O0AkN9grYiWbc1vAYOtKBNDmPvXofqv967x5d953p1fNTg2XJLy/zpgrRaBc0GQg5/lpve6mpee+aBqxjIercez2DUtPSp8tYLJbadmQx328B4EPJP5OQPCTvcmk2AtcCcXCnteo+YXiIeY6O5ginzSEkmWZiu9wIUmIMgppPbNFiC7eDw/V5TiDKvX8ZsYmqP2arvxYULmcVyornbdGfEmBv+fB7xZH/djtoKTFZir1Pmlv6i7MlMhildd2aw0zrOR5ijQKjQIZYgUTX/vEA9KPDqyzYz4OMQFJXV6SlsKCwUCPMT6RipZthJYHeupM0OuB4667Nw4nTefFAJqsWUmFivyzIQuIQQ2Otwu/XoQqpoRb1MILWONI21XAOMEshhvMRtqjkQ+alXzZo/mhyCTYa/G7J5vOH5GxH5HLkN2zu6UDtkpTY8g97yzKChsp3YDRvCMTDR,iv:UPVXsY6iozV0/tLlsx3bEP+u2rrxjf5KRz3M1cOgDNI=,tag:fIQsVEysuvnkR0fRuzTurg==,type:str]
sops:
    age:
        - recipient: age1fddrzze4llgrm87eudneguhpjm3al0h5urkwpvh8xf9wgtghmyfqftr7ue
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiaDZ4dDlDaUJnTmp4aWxG
            WmdXaktQNS93dk5sVE94ZmJkRG1xN1pFMEg4Cjcrd2w2Ti9IZTcxQ1hvR2h0d2tr
            N0cvWFVuZDFIa3BLTjJjbVR3bkxLZDgKLS0tIDhGUXJpcS96RnV5NW9BQndjT0dv
            Zk84Y1FIcURCQkJ4NjhmMVF3UjF1VkUKj/Fw8kYHI9zHqLqC99dEmw2Yl41XWhw8
            VoKoFA0XDT8trSftB2D7BwoEWte7AwXvTNLMb6xZL3eOM7yhpJYmXw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1n3u2cl6w3m693auxqwvayf0pzjg9m3kmraqtepcsf9ysyh4f348sjveq3t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNitPMWJkNStSQ3ptLzdQ
            NWtEREtkTVg2OXZ4QkFYZXdacWs2b0k2WkZJCjQwTkFOS2FnWlg4OHBwamV1VE1m
            TVZtOFZnNVMxVjBCVzZLZGJkdW0wVGsKLS0tIFZiWThHTk5HcGNiNnlMU0RaMWh5
            WmpCa2hUNzJBWmlpZXJ0SHh6Y3lzNHMKalTsbQSP5oJk7bMqhwDlXo+c4BRAu85k
            AY9SHTrJ3q1gtEOWJDe76S+0v6Pao4injc+ZZJHwjFe+332Cjm0oLg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18mxj9jae06at5tv9q6dk2t93v0n7c2lmcuml0qdskea2tncjlafshanl25
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZK1hhV2RGMUVqTVlrZ0Mv
            NkxINUVOM0tGMkZ6aFRxZ2VIQWlKeUwrQjJjCmFiMzlMSWN6RUhHWWhpZVdzN09a
            UFBJaWFWL2VISHNYMlk2eEZrdFFFY00KLS0tIHJnMUtwa2k2Y0s5NmJVbFhvalJO
            Ri9WbTJkYnJSdlpQTTdkNnRwVGxDVFEK1nERy6g8+noh5vxnxJVI+X26ohG5Tch9
            HiWzUlyJTY6rE4lCGGjG/ZhdbhcP78+5yT7rvO8XGmyZ6SMYTsj5eA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zzrwz7qw8ck56c6mrwmd4ytx7zg53c29mk374cqlc570ljgaf52saxuwtz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3YU1hcS8rNG5rcWtSSVR3
            MFlCdlVIWjJNU0VEOXlEUWt5WDhZUVVocjJ3CngzR29EamJhczZzUW14djZybkky
            TGthbTJhSkFXMVZBK2srTHRmZ2R6VzQKLS0tIGhMR1oyVHRFdnBmV2FacDRvZnd6
            SWpVMXBaTTU1YzJIdnMvWmVSWHlJVTAKkzqMIxV4q/rBqbMR6N2JNF68fykEuw/B
            M641CKqiVdtRoSJeoB+SrDkUrVG6mBwNWn4js2ZBvx/SRd7We9EPTg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vetzjh8hc78lrv87fwcf3t5ggn2nsxj2yqu976gh93v902r3d3ks40eug6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ZHg2NkRFb1lhREhBTWF6
            SVdNeVlnM3BFSUlxT3AxUk5WMVlRdDdBMTBjCm52TjhRQlpBZWNoSjYwZkhNMk84
            bmk1VWdtcHQ5UjN5cmtTTWkvM3oxbm8KLS0tIDFaNnVPMEwyblVKalM2RTM3SC9o
            Mmhic2xzM29iSTVlTUk5Q3BvWkU2YVkKF4nVhMYFPE7jjpeMJP9zptE45yXPRESb
            eCXSTKfRG5CixVjF9CaaQ9en1i4otRoER543KZT2pcdfi25TYbXx3A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19jn40tfeespt7dwute2yejc2u5ruthddgcyryp7pvqr5z46653xqjx7rjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFRTd3Vjl5TG1LUjVwNFpJ
            TmFvQVYwY1htUmlybXFsY21ycUl3ZGZ6T3prCk9yMTVUN2RZQjFtUWtIV1pmenR1
            dklVQm5oeGJ4Mk9nMFQwZEpXa251UUEKLS0tIDlRczdvbG8zZ3NlWEpraEliOUhh
            Q2ZMNWYyd2kvWFRCbWhvblVXRTh1bVUKl4beqJvxC5XIyhw/EQoWVVr5EqsrEY+r
            WIN6r16CVatt1XqrxKRDnuOpuSBR9huyUaeJDK78cD6ESG9wcwZtbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T16:23:46Z"
    mac: ENC[AES256_GCM,data:kCw3EFH+V9bNJs3oT/csncOHpWNaxKcREQe6p6yjI8eI+VttWM8koK1AJ1rWFCmGIjoM9om66cLE0NVmaz42H+m13KQC2aSMaWFOf92CsxG0Q5ChxAsgiYeqeR5ACmUal29wRyaMJ9cH+hzHGacwgbyhW7nAkBHIremFpAnPDRY=,iv:qS7j4JSA3Au+QpAWHUkrPhmTUK9XST3G8MwHWR3kR7Y=,tag:NT0lmkQ4ye4hgnmB0mno5Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
